In [1]:
 #importing numpy and pandas which are required for data-preprocessing
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Loading the data

In [2]:
df=pd.read_csv("datathon_train.csv")

In [3]:
df

urls_name  0
0       http://yasli-sad.ru/css/chase/chaseall%20newin...  1
1       http://denizkent.net/wp-admin/js/login.alibaba...  1
2       http://www.marketbiz.net/mbz/wp-includes/js/jq...  1
3       http://guardiaoitau30horas.uniclassdispositivo...  1
4       http://chancejumpers.com/christmas/christmas-h...  0
...                                                   ... ..
100854               http://crop-topsnn.oucreate.com/grn/  1
100855  http://jacksonvillenursinghomelawyers.com/Driv...  1
100856  http://www.smallappliance.com/product.asp?cur=...  0
100857                   http://www.skofija-novomesto.si/  0
100858  http://ferlafashion.com/saint/www.loginalibaba...  1

[100859 rows x 2 columns]

In [4]:
df.head()

urls_name  0
0  http://yasli-sad.ru/css/chase/chaseall%20newin...  1
1  http://denizkent.net/wp-admin/js/login.alibaba...  1
2  http://www.marketbiz.net/mbz/wp-includes/js/jq...  1
3  http://guardiaoitau30horas.uniclassdispositivo...  1
4  http://chancejumpers.com/christmas/christmas-h...  0

In [5]:
df.tail()

urls_name  0
100854               http://crop-topsnn.oucreate.com/grn/  1
100855  http://jacksonvillenursinghomelawyers.com/Driv...  1
100856  http://www.smallappliance.com/product.asp?cur=...  0
100857                   http://www.skofija-novomesto.si/  0
100858  http://ferlafashion.com/saint/www.loginalibaba...  1

In [6]:
df.isnull().sum()

urls_name    0
0            0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100859 entries, 0 to 100858
Data columns (total 2 columns):
 #   Column     Non-Null Count   Dtype 
---  ------     --------------   ----- 
 0   urls_name  100859 non-null  object
 1   0          100859 non-null  int64 
dtypes: int64(1), object(1)
memory usage: 1.5+ MB


In [8]:
df=df.dropna()

In [9]:
df

urls_name  0
0       http://yasli-sad.ru/css/chase/chaseall%20newin...  1
1       http://denizkent.net/wp-admin/js/login.alibaba...  1
2       http://www.marketbiz.net/mbz/wp-includes/js/jq...  1
3       http://guardiaoitau30horas.uniclassdispositivo...  1
4       http://chancejumpers.com/christmas/christmas-h...  0
...                                                   ... ..
100854               http://crop-topsnn.oucreate.com/grn/  1
100855  http://jacksonvillenursinghomelawyers.com/Driv...  1
100856  http://www.smallappliance.com/product.asp?cur=...  0
100857                   http://www.skofija-novomesto.si/  0
100858  http://ferlafashion.com/saint/www.loginalibaba...  1

[100859 rows x 2 columns]

In [10]:
####

In [11]:
df['urls_name']=df['urls_name'].apply(lambda x:x.replace("://"," "))
df['urls_name']=df['urls_name'].apply(lambda x:x.replace("."," "))
df['urls_name']=df['urls_name'].apply(lambda x:x.replace("/"," "))
df['urls_name']=df['urls_name'].apply(lambda x:x.replace("?"," "))
df['urls_name']=df['urls_name'].apply(lambda x:x.replace("%20"," "))
df['urls_name']=df['urls_name'].apply(lambda x:x.replace("-"," "))


In [12]:
df

urls_name  0
0       http yasli sad ru css chase chaseall newinfo_a...  1
1        http denizkent net wp admin js login alibaba com  1
2       http www marketbiz net mbz wp includes js jque...  1
3       http guardiaoitau30horas uniclassdispositivos ...  1
4       http chancejumpers com christmas christmas hou...  0
...                                                   ... ..
100854                 http crop topsnn oucreate com grn   1
100855  http jacksonvillenursinghomelawyers com Drive ...  1
100856  http www smallappliance com product asp cur=US...  0
100857                     http www skofija novomesto si   0
100858  http ferlafashion com saint www loginalibaba c...  1

[100859 rows x 2 columns]

# CountVectorizer

In [13]:
from sklearn.feature_extraction.text import CountVectorizer


In [14]:
vect=CountVectorizer()
vector=vect.fit_transform(df['urls_name'])

In [15]:
vector

<100859x170196 sparse matrix of type '<class 'numpy.int64'>'
	with 749483 stored elements in Compressed Sparse Row format>

In [16]:
vector.shape

(100859, 170196)

# TfidfVectorizer

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer


In [18]:
vect1=TfidfVectorizer
vector1=vect.fit_transform(df['urls_name'])

In [19]:
vector1.shape

(100859, 170196)

In [20]:
vector1

<100859x170196 sparse matrix of type '<class 'numpy.int64'>'
	with 749483 stored elements in Compressed Sparse Row format>

In [21]:
###Splitting the data

In [22]:
y=df['0']

In [23]:
y

0         1
1         1
2         1
3         1
4         0
         ..
100854    1
100855    1
100856    0
100857    0
100858    1
Name: 0, Length: 100859, dtype: int64

In [24]:
x=vector

In [25]:
x

<100859x170196 sparse matrix of type '<class 'numpy.int64'>'
	with 749483 stored elements in Compressed Sparse Row format>

In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [27]:
from sklearn.model_selection import KFold
import numpy as np

k_fold = KFold(n_splits=5)
for indices_train, indices_test in k_fold.split(x):
    print(indices_train, indices_test)


[ 20172  20173  20174 ... 100856 100857 100858] [    0     1     2 ... 20169 20170 20171]
[     0      1      2 ... 100856 100857 100858] [20172 20173 20174 ... 40341 40342 40343]
[     0      1      2 ... 100856 100857 100858] [40344 40345 40346 ... 60513 60514 60515]
[     0      1      2 ... 100856 100857 100858] [60516 60517 60518 ... 80685 80686 80687]
[    0     1     2 ... 80685 80686 80687] [ 80688  80689  80690 ... 100856 100857 100858]


In [28]:
from xgboost import XGBClassifier

In [29]:
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score
model=XGBClassifier()
model.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)

In [30]:
model.predict(x_test)

array([0, 0, 0, ..., 1, 0, 0])

In [31]:
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression()
model1.fit(x_train,y_train)

C:\Users\jyoth\OneDrive\Desktop\PSP\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [32]:
model1.predict(x_test)

array([0, 0, 0, ..., 1, 1, 0], dtype=int64)

In [33]:
from sklearn.neighbors import KNeighborsClassifier
model2=KNeighborsClassifier()
model2.fit(x_train,y_train)

KNeighborsClassifier()

In [34]:
model2.predict(x_test)

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [35]:
from sklearn.tree import DecisionTreeClassifier
model3 = DecisionTreeClassifier()
model3.fit(x_train,y_train)

DecisionTreeClassifier()

In [36]:
model3.predict(x_test)

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [ ]:
print(":mfkdnf")

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier
model4= ExtraTreesClassifier()
model4.fit(x_train,y_train)

In [ ]:
model4.predict(x_test)

In [ ]:
import catboost as ctb

In [ ]:
model5=ctb.CatBoostClassifier()
model5.fit(x_train,y_train)