In [1]:
 #importing numpy and pandas which are required for data-preprocessing

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Loading the data

In [2]:
df=pd.read_csv("datathon_train.csv")


In [3]:
df1=pd.read_csv("testing_data.csv",header=None)

In [4]:
df1

0
0                       http://www.skofija-novomesto.si/
1      http://ferlafashion.com/saint/www.loginalibaba...
2                               http://spatrendonline.hu
3                               http://defensasur.com.ar
4                     http://www.digitalvd.de/dvds/37399
...                                                  ...
25214                               http://mohaseban.org
25215                          https://www.la-croix.com/
25216                              http://bit.ly/2CbFTLv
25217  http://beautyatjessicas.com.au/wp-content/uplo...
25218  http://www.la-taverne-des-aventuriers.com/t457...

[25219 rows x 1 columns]

In [5]:
df1

0
0                       http://www.skofija-novomesto.si/
1      http://ferlafashion.com/saint/www.loginalibaba...
2                               http://spatrendonline.hu
3                               http://defensasur.com.ar
4                     http://www.digitalvd.de/dvds/37399
...                                                  ...
25214                               http://mohaseban.org
25215                          https://www.la-croix.com/
25216                              http://bit.ly/2CbFTLv
25217  http://beautyatjessicas.com.au/wp-content/uplo...
25218  http://www.la-taverne-des-aventuriers.com/t457...

[25219 rows x 1 columns]

In [6]:
df.head()

urls_name  0
0  http://yasli-sad.ru/css/chase/chaseall%20newin...  1
1  http://denizkent.net/wp-admin/js/login.alibaba...  1
2  http://www.marketbiz.net/mbz/wp-includes/js/jq...  1
3  http://guardiaoitau30horas.uniclassdispositivo...  1
4  http://chancejumpers.com/christmas/christmas-h...  0

In [7]:
df.tail()

urls_name  0
100854               http://crop-topsnn.oucreate.com/grn/  1
100855  http://jacksonvillenursinghomelawyers.com/Driv...  1
100856  http://www.smallappliance.com/product.asp?cur=...  0
100857                   http://www.skofija-novomesto.si/  0
100858  http://ferlafashion.com/saint/www.loginalibaba...  1

In [8]:
df.isnull().sum()

urls_name    0
0            0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100859 entries, 0 to 100858
Data columns (total 2 columns):
 #   Column     Non-Null Count   Dtype 
---  ------     --------------   ----- 
 0   urls_name  100859 non-null  object
 1   0          100859 non-null  int64 
dtypes: int64(1), object(1)
memory usage: 1.5+ MB


In [10]:
df=df.dropna()

In [11]:
df

urls_name  0
0       http://yasli-sad.ru/css/chase/chaseall%20newin...  1
1       http://denizkent.net/wp-admin/js/login.alibaba...  1
2       http://www.marketbiz.net/mbz/wp-includes/js/jq...  1
3       http://guardiaoitau30horas.uniclassdispositivo...  1
4       http://chancejumpers.com/christmas/christmas-h...  0
...                                                   ... ..
100854               http://crop-topsnn.oucreate.com/grn/  1
100855  http://jacksonvillenursinghomelawyers.com/Driv...  1
100856  http://www.smallappliance.com/product.asp?cur=...  0
100857                   http://www.skofija-novomesto.si/  0
100858  http://ferlafashion.com/saint/www.loginalibaba...  1

[100859 rows x 2 columns]

In [12]:
df['urls_name']=df['urls_name'].apply(lambda x:x.replace("://"," "))
df['urls_name']=df['urls_name'].apply(lambda x:x.replace("."," "))
df['urls_name']=df['urls_name'].apply(lambda x:x.replace("/"," "))
df['urls_name']=df['urls_name'].apply(lambda x:x.replace("?"," "))
df['urls_name']=df['urls_name'].apply(lambda x:x.replace("%20"," "))
df['urls_name']=df['urls_name'].apply(lambda x:x.replace("-"," "))


In [13]:
df1.iloc[:,0] = df1.iloc[:,0].apply(lambda x:x.replace("://"," "))
df1.iloc[:,0] = df1.iloc[:,0].apply(lambda x:x.replace("."," "))
df1.iloc[:,0] = df1.iloc[:,0].apply(lambda x:x.replace("/"," "))
df1.iloc[:,0] = df1.iloc[:,0].apply(lambda x:x.replace("?"," "))
df1.iloc[:,0] = df1.iloc[:,0].apply(lambda x:x.replace("%20"," "))
df1.iloc[:,0] = df1.iloc[:,0].apply(lambda x:x.replace("-"," "))


In [14]:
df1

0
0                         http www skofija novomesto si 
1      http ferlafashion com saint www loginalibaba c...
2                                 http spatrendonline hu
3                                 http defensasur com ar
4                       http www digitalvd de dvds 37399
...                                                  ...
25214                                 http mohaseban org
25215                            https www la croix com 
25216                                http bit ly 2CbFTLv
25217  http beautyatjessicas com au wp content upload...
25218  http www la taverne des aventuriers com t4575 ...

[25219 rows x 1 columns]

# CountVectorizer

In [15]:
from sklearn.feature_extraction.text import CountVectorizer


In [16]:
vect=CountVectorizer()
vector=vect.fit_transform(df['urls_name'])

In [17]:
vector

<100859x170196 sparse matrix of type '<class 'numpy.int64'>'
	with 749483 stored elements in Compressed Sparse Row format>

In [18]:
vector.shape

(100859, 170196)

# TfidfVectorizer

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer


In [20]:
vect1=TfidfVectorizer
vector1=vect.fit_transform(df['urls_name'])

In [21]:
vector1.shape

(100859, 170196)

In [22]:
vector1

<100859x170196 sparse matrix of type '<class 'numpy.int64'>'
	with 749483 stored elements in Compressed Sparse Row format>

# Splitting the data

In [23]:
y=df['0']

In [24]:
y

0         1
1         1
2         1
3         1
4         0
         ..
100854    1
100855    1
100856    0
100857    0
100858    1
Name: 0, Length: 100859, dtype: int64

In [25]:
x=vector

In [26]:
x

<100859x170196 sparse matrix of type '<class 'numpy.int64'>'
	with 749483 stored elements in Compressed Sparse Row format>

In [27]:
from sklearn.model_selection import KFold
import numpy as np

k_fold = KFold(n_splits=5)
for indices_train, indices_test in k_fold.split(x):
    print(indices_train, indices_test)

[ 20172  20173  20174 ... 100856 100857 100858] [    0     1     2 ... 20169 20170 20171]
[     0      1      2 ... 100856 100857 100858] [20172 20173 20174 ... 40341 40342 40343]
[     0      1      2 ... 100856 100857 100858] [40344 40345 40346 ... 60513 60514 60515]
[     0      1      2 ... 100856 100857 100858] [60516 60517 60518 ... 80685 80686 80687]
[    0     1     2 ... 80685 80686 80687] [ 80688  80689  80690 ... 100856 100857 100858]


# Training of data

In [28]:
from sklearn.model_selection import train_test_split
x_train,y_train,x_test,y_test=train_test_split(x,y,test_size=0.2)

In [29]:
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.metrics import mean_squared_error
def train(model, X, y):
    # train the model
    x_train, x_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=42)
    model.fit(x_train, y_train)
    
    # predict the training set
    pred = model.predict(x_test)
    print("accuracy",model.score(x_test,y_test))

# Logistic Regression

In [30]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
train(model,x,y)

accuracy 0.9265813999603411


C:\Users\jyoth\OneDrive\Desktop\PSP\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# MultinomialNB

In [31]:
from sklearn.naive_bayes import MultinomialNB
model2 = MultinomialNB()
train(model2,x,y)

accuracy 0.930299424945469


# Saving in pickle

In [32]:
import pickle
filename="deep.pkl"
pickle.dump(model,open(filename,'wb'))

In [33]:
load_model=pickle.load(open(filename,'rb'))

In [34]:
vector=vect.transform(df1.iloc[:,0])

In [35]:
y_pred = load_model.predict(vector)

In [36]:
test_df = pd.DataFrame()

In [37]:
test_df['a'] = y_pred

In [39]:
test_df.to_csv(r'C:\Users\jyoth\Desktop\model\res8.csv', index = False)

In [40]:
test_df

a
0      0
1      1
2      0
3      0
4      0
...   ..
25214  0
25215  0
25216  1
25217  1
25218  0

[25219 rows x 1 columns]

# XGBClassifier

In [41]:
from xgboost import XGBClassifier

In [42]:
model1=XGBClassifier()
train(model1,x,y)

accuracy 0.8824112631370216


In [43]:
filename="deep1.pkl"
pickle.dump(model1,open(filename,'wb'))

In [44]:
load_model1=pickle.load(open(filename,'rb'))

In [45]:
vector=vect.transform(df1.iloc[:,0])

In [46]:
y_pred = load_model1.predict(vector)

In [47]:
test_df1 = pd.DataFrame()

In [48]:
test_df1['a'] = y_pred

In [49]:
test_df1.to_csv(r'C:\Users\jyoth\Desktop\model\res5.csv', index = False)

In [50]:
filename="deep2.pkl"
pickle.dump(model2,open(filename,'wb'))

In [51]:
load_model2=pickle.load(open(filename,'rb'))

In [52]:
vector=vect.transform(df1.iloc[:,0])


In [53]:
y_pred = load_model2.predict(vector)

In [54]:
test_df2 = pd.DataFrame()

In [55]:
test_df2['a'] = y_pred

In [56]:
test_df2.to_csv(r'C:\Users\jyoth\Desktop\model\res6.csv', index = False)